### ISSUE TITLE
print warning if processing empty pool directory

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#173]

**Comment by jtluka** [comment]
Note that the patch you posted is for a different issue.

**Comment by olichtne** [comment]
This was part of LNST since I moved pool definition into it's own config section in 9e2b4ae50ee6b8f28e26b5ccd3d97a6dce15ff4a. It was then further updated to work with "lnst-ctl list-pools" in b4ff4fd2a48fca07224bb77f13796563ae581661. I'm guessing we can close this? Or is the point of this issue something else?

**Comment by jiriprochazka** [comment]
I think the issue was aimed on list_pools action where it didn't work correctly.

**Comment by olichtne** [comment]
Ok, so we can close it then?
